# Generated by Django 3.2.5 on 2021-08-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('discription', models.TextField(max_length=50)),
                ('wallpapers', models.ImageField(upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='WallpaperLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallpapers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.wallpaper')),
            ],
        ),
        migrations.CreateModel(
            name='WallpaperTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=10)),
                ('wallpaperm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.wallpaper')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.wallpaperlikes'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.wallpapertags'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
