# Generated by Django 3.2.5 on 2021-08-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_usersaccount'),
        ('walls', '0002_auto_20210810_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaperlikes',
            name='users',
        ),
        migrations.RemoveField(
            model_name='wallpaperlikes',
            name='wallpapers',
        ),
        migrations.RemoveField(
            model_name='wallpapertags',
            name='wallpaperm',
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
        migrations.DeleteModel(
            name='WallpaperLikes',
        ),
        migrations.DeleteModel(
            name='WallpaperTags',
        ),
    ]
