# Generated by Django 3.2.5 on 2021-08-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0004_tag_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
