# Generated by Django 3.2.5 on 2021-08-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0008_tag_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
